// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

/* eslint-disable */
export type CoercedEnvSchema = {
  /**
   * **OP_TOKEN**  
   * 1Password service account token  
   */
  OP_TOKEN?: string;
  
  /**
   * **OP_ENV_ID**  
   * 1Password environment ID to load secrets from  
   */
  OP_ENV_ID?: string;
  
  /**
   * **COPILOT_HOST**  
   * Bind host (use 0.0.0.0 inside Docker)  
   */
  COPILOT_HOST?: string;
  
  /**
   * **COPILOT_API_KEY_AUTH**  
   * API key authentication — requests without this key are dropped  
   */
  COPILOT_API_KEY_AUTH?: string;
  
  /**
   * **SENTRY_DSN**  
   * Sentry error monitoring DSN  
   */
  SENTRY_DSN?: string;
  
  /**
   * **GROQ_API_KEY**  
   * Groq API key for voice transcription (Whisper STT)  
   */
  GROQ_API_KEY?: string;
  
};


declare module 'varlock/env' {
  export interface TypedEnvSchema extends Readonly<CoercedEnvSchema> {}
  export interface PublicTypedEnvSchema extends Readonly<Pick<CoercedEnvSchema, 'OP_TOKEN' | 'OP_ENV_ID' | 'COPILOT_HOST' | 'COPILOT_API_KEY_AUTH' | 'SENTRY_DSN' | 'GROQ_API_KEY'>> {}
}


export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]:
    CoercedEnvSchema[Property] extends string ? CoercedEnvSchema[Property]
      : (CoercedEnvSchema[Property] extends boolean ? ('true' | 'false') : string)
};

declare global {

  // add types for global import.meta.env
  interface ImportMetaEnv extends EnvSchemaAsStrings {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends EnvSchemaAsStrings {}
  }
}