// AUTO-GENERATED build helper — reads the single-file Vite build output and
// emits it as a TypeScript string module the Hono server can import.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const distHtmlPath = join(__dirname, "..", "dist", "index.html")
const outPath = join(
  __dirname,
  "..",
  "..",
  "src",
  "routes",
  "dashboard",
  "page-generated.ts",
)

const html = readFileSync(distHtmlPath, "utf8")

mkdirSync(dirname(outPath), { recursive: true })

const contents = `// AUTO-GENERATED by \`npm run build\` in ui/ — do not edit.
export const DASHBOARD_HTML: string = ${JSON.stringify(html)}
`

writeFileSync(outPath, contents)

console.log(`Wrote ${outPath} (${html.length} bytes of embedded HTML)`)
