import type {
  ResponseInputItem,
  ResponsesPayload,
} from "~/services/copilot/create-responses"

const UNRECOVERED_COMPACTION_SUMMARY =
  "[Previous conversation context was compacted]"

export const getResponsesRequestOptions = (
  payload: ResponsesPayload,
): { vision: boolean; initiator: "agent" | "user" } => {
  const vision = hasVisionInput(payload)
  const initiator = hasAgentInitiator(payload) ? "agent" : "user"

  return { vision, initiator }
}

/**
 * Expand compaction items into plain assistant messages and strip
 * encrypted_content from reasoning items.
 *
 * Compaction items carry encrypted_content tied to the specific API token
 * that created them. Since this proxy routes to different Copilot tokens,
 * compaction items must be converted to plain messages to avoid:
 *   - "could not be verified" errors (wrong token)
 *   - "Missing required parameter" errors (stripped content)
 *
 * Proxy-generated "cmp_" items have base64-encoded summaries we can decode.
 * Native compaction items have opaque encrypted data — we try to extract
 * any readable text from the item fields (summary, text) before falling
 * back to a placeholder.
 *
 * Reasoning items also have encrypted_content stripped for the same reason.
 */
export const expandCompactionItems = (payload: ResponsesPayload): void => {
  if (!Array.isArray(payload.input)) return

  payload.input = payload.input.map((item) => {
    const record = item as Record<string, unknown>

    // Convert compaction items into plain messages
    if (record.type === "compaction") {
      const summary = extractCompactionSummary(record)

      return {
        type: "message",
        role: "assistant",
        content: `[Previous conversation summary]\n${summary}`,
      } as ResponseInputItem
    }

    // Strip encrypted_content from reasoning items — upstream can't verify
    // tokens generated by a different Copilot session/account
    if (record.type === "reasoning" && "encrypted_content" in record) {
      const { encrypted_content: _, ...rest } = record
      return rest as ResponseInputItem
    }

    return item
  })
}

/**
 * Try every available avenue to recover useful text from a compaction item.
 *
 * Priority:
 *  1. Proxy-generated items (cmp_ prefix) — base64-decode encrypted_content
 *  2. Any explicit "summary" or "text" field on the item
 *  3. Try base64-decoding encrypted_content even without cmp_ prefix
 *     (it may contain readable UTF-8 if generated by another compatible proxy)
 *  4. Fall back to a compact placeholder
 */
const extractCompactionSummary = (record: Record<string, unknown>): string => {
  const id = typeof record.id === "string" ? record.id : ""
  const encrypted =
    typeof record.encrypted_content === "string" ?
      record.encrypted_content
    : null

  // 1. Proxy-generated items — base64 summary
  if (encrypted && id.startsWith("cmp_")) {
    const decoded = tryBase64Decode(encrypted)
    if (decoded) return decoded
  }

  // 2. Explicit summary / text fields some implementations attach
  const fromFields = extractSummaryFields(record)
  if (fromFields) return fromFields

  // 3. Speculatively try base64-decoding encrypted_content — even without
  //    cmp_ prefix it may be readable if generated by a compatible proxy
  if (encrypted) {
    const decoded = tryBase64DecodeReadable(encrypted)
    if (decoded) return decoded
  }

  // 4. Last resort
  return UNRECOVERED_COMPACTION_SUMMARY
}

/** Decode base64 to UTF-8, returning null on failure or empty result. */
const tryBase64Decode = (data: string): string | null => {
  try {
    const decoded = Buffer.from(data, "base64").toString("utf8")
    return decoded.length > 0 ? decoded : null
  } catch {
    return null
  }
}

/** Decode base64 and return text only if it looks like readable UTF-8. */
const tryBase64DecodeReadable = (data: string): string | null => {
  const decoded = tryBase64Decode(data)
  if (!decoded) return null
  if (decoded.includes("\uFFFD")) return null
  const printable = decoded.replaceAll(/[^\x20-\x7E\n\r\t]/g, "")
  return printable.length / decoded.length > 0.8 ? decoded : null
}

/** Extract text from summary/text fields that some implementations attach. */
const extractSummaryFields = (
  record: Record<string, unknown>,
): string | null => {
  const parts: Array<string> = []
  if (Array.isArray(record.summary)) {
    for (const entry of record.summary) {
      const text = extractEntryText(entry)
      if (text) parts.push(text)
    }
  }
  if (typeof record.summary === "string" && record.summary) {
    parts.push(record.summary)
  }
  if (typeof record.text === "string" && record.text) {
    parts.push(record.text)
  }
  return parts.length > 0 ? parts.join("\n") : null
}

const extractEntryText = (entry: unknown): string | null => {
  if (typeof entry === "string") return entry
  if (
    typeof entry === "object"
    && entry !== null
    && typeof (entry as Record<string, unknown>).text === "string"
  ) {
    return (entry as Record<string, unknown>).text as string
  }
  return null
}
export const hasAgentInitiator = (payload: ResponsesPayload): boolean => {
  // Refactor `isAgentCall` logic to check only the last message in the history rather than any message. This prevents valid user messages from being incorrectly flagged as agent calls due to previous assistant history, ensuring proper credit consumption for multi-turn conversations.
  const lastItem = getPayloadItems(payload).at(-1)
  if (!lastItem) {
    return false
  }
  if (!("role" in lastItem) || !lastItem.role) {
    return true
  }
  const role =
    typeof lastItem.role === "string" ? lastItem.role.toLowerCase() : ""
  return role === "assistant"
}

export const hasVisionInput = (payload: ResponsesPayload): boolean => {
  const values = getPayloadItems(payload)
  return values.some((item) => containsVisionContent(item))
}

const getPayloadItems = (
  payload: ResponsesPayload,
): Array<ResponseInputItem> => {
  const result: Array<ResponseInputItem> = []

  const { input } = payload

  if (Array.isArray(input)) {
    result.push(...input)
  }

  return result
}

const containsVisionContent = (value: unknown): boolean => {
  if (!value) return false

  if (Array.isArray(value)) {
    return value.some((entry) => containsVisionContent(entry))
  }

  if (typeof value !== "object") {
    return false
  }

  const record = value as Record<string, unknown>
  const type =
    typeof record.type === "string" ? record.type.toLowerCase() : undefined

  if (type === "input_image") {
    return true
  }

  if (Array.isArray(record.content)) {
    return record.content.some((entry) => containsVisionContent(entry))
  }

  return false
}
