import type {
  ResponseInputItem,
  ResponsesPayload,
} from "~/services/copilot/create-responses"

export const getResponsesRequestOptions = (
  payload: ResponsesPayload,
): { vision: boolean; initiator: "agent" | "user" } => {
  const vision = hasVisionInput(payload)
  const initiator = hasAgentInitiator(payload) ? "agent" : "user"

  return { vision, initiator }
}

/**
 * Expand proxy-generated compaction compatibility items back into regular messages
 * and strip encrypted_content from all input items that carry it.
 *
 * Proxy-generated "cmp_" items use base64-encoded summaries that upstream cannot
 * decrypt — these are expanded into plain assistant messages.
 *
 * Native compaction and reasoning items carry encrypted_content that is
 * cryptographically tied to the specific API token that generated them.
 * Since this proxy may route requests to different Copilot tokens, these
 * fields will cause 400 "could not be verified" errors and must be stripped.
 */
export const expandCompactionItems = (payload: ResponsesPayload): void => {
  if (!Array.isArray(payload.input)) return

  payload.input = payload.input.map((item) => {
    const record = item as Record<string, unknown>

    // Expand proxy-generated compaction items into plain messages
    if (
      record.type === "compaction"
      && typeof record.encrypted_content === "string"
      && typeof record.id === "string"
      && record.id.startsWith("cmp_")
    ) {
      let summary: string
      try {
        summary = Buffer.from(record.encrypted_content, "base64").toString(
          "utf8",
        )
      } catch {
        summary = record.encrypted_content
      }

      return {
        type: "message",
        role: "assistant",
        content: `[Previous conversation summary]\n${summary}`,
      } as ResponseInputItem
    }

    // Strip encrypted_content from any item — upstream can't verify tokens
    // generated by a different Copilot session/account
    if ("encrypted_content" in record) {
      const { encrypted_content: _, ...rest } = record
      return rest as ResponseInputItem
    }

    return item
  })
}

export const hasAgentInitiator = (payload: ResponsesPayload): boolean => {
  // Refactor `isAgentCall` logic to check only the last message in the history rather than any message. This prevents valid user messages from being incorrectly flagged as agent calls due to previous assistant history, ensuring proper credit consumption for multi-turn conversations.
  const lastItem = getPayloadItems(payload).at(-1)
  if (!lastItem) {
    return false
  }
  if (!("role" in lastItem) || !lastItem.role) {
    return true
  }
  const role =
    typeof lastItem.role === "string" ? lastItem.role.toLowerCase() : ""
  return role === "assistant"
}

export const hasVisionInput = (payload: ResponsesPayload): boolean => {
  const values = getPayloadItems(payload)
  return values.some((item) => containsVisionContent(item))
}

const getPayloadItems = (
  payload: ResponsesPayload,
): Array<ResponseInputItem> => {
  const result: Array<ResponseInputItem> = []

  const { input } = payload

  if (Array.isArray(input)) {
    result.push(...input)
  }

  return result
}

const containsVisionContent = (value: unknown): boolean => {
  if (!value) return false

  if (Array.isArray(value)) {
    return value.some((entry) => containsVisionContent(entry))
  }

  if (typeof value !== "object") {
    return false
  }

  const record = value as Record<string, unknown>
  const type =
    typeof record.type === "string" ? record.type.toLowerCase() : undefined

  if (type === "input_image") {
    return true
  }

  if (Array.isArray(record.content)) {
    return record.content.some((entry) => containsVisionContent(entry))
  }

  return false
}
