import type {
  ResponseInputItem,
  ResponsesPayload,
} from "~/services/copilot/create-responses"

export const getResponsesRequestOptions = (
  payload: ResponsesPayload,
): { vision: boolean; initiator: "agent" | "user" } => {
  const vision = hasVisionInput(payload)
  const initiator = hasAgentInitiator(payload) ? "agent" : "user"

  return { vision, initiator }
}

/**
 * Expand compaction items into plain assistant messages and strip
 * encrypted_content from reasoning items.
 *
 * Compaction items carry encrypted_content tied to the specific API token
 * that created them. Since this proxy routes to different Copilot tokens,
 * compaction items must be converted to plain messages to avoid:
 *   - "could not be verified" errors (wrong token)
 *   - "Missing required parameter" errors (stripped content)
 *
 * Proxy-generated "cmp_" items have base64-encoded summaries we can decode.
 * Native compaction items have opaque encrypted data we can't read — these
 * are replaced with a placeholder since the summary is lost.
 *
 * Reasoning items also have encrypted_content stripped for the same reason.
 */
export const expandCompactionItems = (payload: ResponsesPayload): void => {
  if (!Array.isArray(payload.input)) return

  payload.input = payload.input.map((item) => {
    const record = item as Record<string, unknown>

    // Convert compaction items into plain messages
    if (record.type === "compaction") {
      let summary = "[Previous conversation context was compacted]"

      // Proxy-generated items (cmp_ prefix) have base64 summaries we can decode
      if (
        typeof record.encrypted_content === "string"
        && typeof record.id === "string"
        && record.id.startsWith("cmp_")
      ) {
        try {
          summary = Buffer.from(record.encrypted_content, "base64").toString(
            "utf8",
          )
        } catch {
          summary = record.encrypted_content
        }
      }

      return {
        type: "message",
        role: "assistant",
        content: `[Previous conversation summary]\n${summary}`,
      } as ResponseInputItem
    }

    // Strip encrypted_content from reasoning items — upstream can't verify
    // tokens generated by a different Copilot session/account
    if (record.type === "reasoning" && "encrypted_content" in record) {
      const { encrypted_content: _, ...rest } = record
      return rest as ResponseInputItem
    }

    return item
  })
}

export const hasAgentInitiator = (payload: ResponsesPayload): boolean => {
  // Refactor `isAgentCall` logic to check only the last message in the history rather than any message. This prevents valid user messages from being incorrectly flagged as agent calls due to previous assistant history, ensuring proper credit consumption for multi-turn conversations.
  const lastItem = getPayloadItems(payload).at(-1)
  if (!lastItem) {
    return false
  }
  if (!("role" in lastItem) || !lastItem.role) {
    return true
  }
  const role =
    typeof lastItem.role === "string" ? lastItem.role.toLowerCase() : ""
  return role === "assistant"
}

export const hasVisionInput = (payload: ResponsesPayload): boolean => {
  const values = getPayloadItems(payload)
  return values.some((item) => containsVisionContent(item))
}

const getPayloadItems = (
  payload: ResponsesPayload,
): Array<ResponseInputItem> => {
  const result: Array<ResponseInputItem> = []

  const { input } = payload

  if (Array.isArray(input)) {
    result.push(...input)
  }

  return result
}

const containsVisionContent = (value: unknown): boolean => {
  if (!value) return false

  if (Array.isArray(value)) {
    return value.some((entry) => containsVisionContent(entry))
  }

  if (typeof value !== "object") {
    return false
  }

  const record = value as Record<string, unknown>
  const type =
    typeof record.type === "string" ? record.type.toLowerCase() : undefined

  if (type === "input_image") {
    return true
  }

  if (Array.isArray(record.content)) {
    return record.content.some((entry) => containsVisionContent(entry))
  }

  return false
}
